# Configuration file for relationship graph generation

# Output settings
output_dir: ./qa_toy

# Character settings
num_characters: 4                        # Number of characters to generate
character_names_file: data/characters.txt              # Optional file with character names (one per line)    
relations_file: data/relations.txt

# Relationship settings
min_relationships: 1                      # Minimum number of relationships per character
max_relationships: 3                      # Maximum number of relationships per character
random_seed: 30 
gendered: true                        # Whether to enforce gender exclusivity
                        # Random seed for reproducibility

# Training data generation
generate_training: true                  # Set to true to automatically generate training data
training_data_format: qa  
num_paraphrases: 0                     # Number of paraphrases to generate per question
openai_model: gpt-4o              # OpenAI model to use for paraphrasing
