# Configuration file for relationship graph generation

# Output settings
output_dir: ./qa_sn

# Character settings
num_characters: 200                       
character_names_file: data/characters.txt   
relations_file: data/relations.txt

# Relationship settings
min_relationships: 1                     
max_relationships: 1                     
random_seed: 42  
gendered: false                       

# Training data generation
generate_training: true                 
training_data_format: qa  
num_paraphrases: 4                      
openai_model: gpt-4o             
