# Configuration file for relationship graph generation

# Output settings
output_dir: ./qa_cn

# Character settings
num_characters: 50                        # Number of characters to generate
character_names_file: data/characters.txt              # Optional file with character names (one per line)    
relations_file: data/relations.txt

# Relationship settings
min_relationships: 1                      # Minimum number of relationships per character
max_relationships: 3                      # Maximum number of relationships per character
random_seed: 42                          # Random seed for reproducibility
gendered: false                        # Whether to enforce gender exclusivity

# Training data generation
generate_training: true                  # Set to true to automatically generate training data
training_data_format: qa  
num_paraphrases: 4                       # Number of paraphrases to generate per question
openai_model: gpt-4o              # OpenAI model to use for paraphrasing
